name: TemplatePlugin
version: ${version}
main: me.gregzee.pluginname.PluginName
api-version: '1.20'
authors: [ Gregzee ]
description: Your plugin description here.
load: POSTWORLD
depend: [CommandAPI]
libraries:
  - de.exlll:configlib-yaml:${configlibVersion}
  - de.exlll:configlib-paper:${configlibVersion}
